### PR TITLE
Added linking to community maintained manifests

### PR DESCRIPTION
**Pull request by mbbroberg**
If you can confirm that this version supports 1.4.8 and you like the phrasing, please merge. If not, lmk what you'd prefer here! Thanks @jbussdieker

### CODE REVIEW

**Comment by jbussdieker** [comment]
@mjbrender that looks like the wrong link.

**Comment by mbbroberg** [comment]
Hey @jbussdieker - that's the link I intended since I'd like to direct people to the public goal.

**Comment by mbbroberg** [comment]
Glad to point directly to the repo as well: https://github.com/basho-labs/puppet-riak

**Comment by jbussdieker** [comment]
I'm confused what the meetup strategy has to do with this.

**Comment by mbbroberg** [comment]
:facepunch: to me. Totally missed it despite you pointing it out. Thanks @jbussdieker - editing now!

**Comment by mbbroberg** [comment]
There we go. Thanks @jbussdieker.

**Comment by jbussdieker** [comment]
Merged!

**Comment by mbbroberg** [comment]
You rock! @jbussdieker, you'll dig seeing all the activity over here too: https://github.com/basho-labs/puppet-riak

^ While you might not have all the time to code with us, definitely speak up when you want!

**Pull request merged**
